org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m

# Use these after you stop touching your settings:
# org.gradle.configuration-cache=true
# org.gradle.caching=true


projectName=Modjam
projectGroup=net.wanmine
projectVersion=1.0.0
projectDescription=Wan's Modjam

# Hytale

hytale.group=WanMine
hytale.main=net.wanmine.Modjam.ModjamPlugin
hytale.authors=WanMine,F36e,FonnyFofo,ImBau,Huggeitor
hytale.website=https://wanmine.net
hytale.includeAssetPack = true